apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  ports:
    - name: web-port
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: jenkins-agent
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
        - image: cwansart/jenkins-podman-slave:3
          name: jenkins-podman-slave
          imagePullPolicy: Always
          securityContext:
            - privileged
          volumeMounts:
            - name: jenkins-agent-volume
              mountPath: /var/lib/containers/storage
      volumes:
        - name: jenkins-agent-volume
          persistentVolumeClaim:
            claimName: jenkins-agent-volume-claim
