apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-slim
          name: jenkins
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
    - name: web-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: build-executor-port
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    app: jenkins
  type: NodePort