apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  ports:
    - name: web-port
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: jenkins-agent
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-agent
  name: jenkins-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent
  template:
    metadata:
      labels:
        app: jenkins-agent
    spec:
      containers:
        - image: cwansart/jenkins-podman-slave:1-autoconnect
          name: jenkins-podman-slave
          imagePullPolicy: Always
