apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - image: sonatype/nexus3:3.19.1
          name: nexus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  ports:
    - name: web-port
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: docker-registry-port
      port: 10080
      protocol: TCP
      targetPort: 10080
  selector:
    app: nexus
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-slim
          name: jenkins
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
    - name: web-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: build-executor-port
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    app: jenkins
  type: NodePort